#!/bin/bash

SCRIPTPATH="$( cd -- "$(dirname "$(realpath "$0")")" >/dev/null 2>&1 ; pwd -P )"
LIBPATH=${SCRIPTPATH}/lib

if [ -d $LIBPATH ]; then
    site_packages_dir=$(find ${LIBPATH} -type d -name "site-packages")

    export PYTHONPATH=${site_packages_dir}:$PYTHONPATH
fi

PYTHONSTARTUP=${SCRIPTPATH}/stfpy_init.py python $@
