from stfpy.stf_lib.stf_reg_def cimport *

cpdef enum STF_REG:
    STF_REG_X0 = <STF_REG_int> _STF_REG_X0
    STF_REG_X1 = <STF_REG_int> _STF_REG_X1
    STF_REG_X2 = <STF_REG_int> _STF_REG_X2
    STF_REG_X3 = <STF_REG_int> _STF_REG_X3
    STF_REG_X4 = <STF_REG_int> _STF_REG_X4
    STF_REG_X5 = <STF_REG_int> _STF_REG_X5
    STF_REG_X6 = <STF_REG_int> _STF_REG_X6
    STF_REG_X7 = <STF_REG_int> _STF_REG_X7
    STF_REG_X8 = <STF_REG_int> _STF_REG_X8
    STF_REG_X9 = <STF_REG_int> _STF_REG_X9
    STF_REG_X10 = <STF_REG_int> _STF_REG_X10
    STF_REG_X11 = <STF_REG_int> _STF_REG_X11
    STF_REG_X12 = <STF_REG_int> _STF_REG_X12
    STF_REG_X13 = <STF_REG_int> _STF_REG_X13
    STF_REG_X14 = <STF_REG_int> _STF_REG_X14
    STF_REG_X15 = <STF_REG_int> _STF_REG_X15
    STF_REG_X16 = <STF_REG_int> _STF_REG_X16
    STF_REG_X17 = <STF_REG_int> _STF_REG_X17
    STF_REG_X18 = <STF_REG_int> _STF_REG_X18
    STF_REG_X19 = <STF_REG_int> _STF_REG_X19
    STF_REG_X20 = <STF_REG_int> _STF_REG_X20
    STF_REG_X21 = <STF_REG_int> _STF_REG_X21
    STF_REG_X22 = <STF_REG_int> _STF_REG_X22
    STF_REG_X23 = <STF_REG_int> _STF_REG_X23
    STF_REG_X24 = <STF_REG_int> _STF_REG_X24
    STF_REG_X25 = <STF_REG_int> _STF_REG_X25
    STF_REG_X26 = <STF_REG_int> _STF_REG_X26
    STF_REG_X27 = <STF_REG_int> _STF_REG_X27
    STF_REG_X28 = <STF_REG_int> _STF_REG_X28
    STF_REG_X29 = <STF_REG_int> _STF_REG_X29
    STF_REG_X30 = <STF_REG_int> _STF_REG_X30
    STF_REG_X31 = <STF_REG_int> _STF_REG_X31

    # 32 floating point registers
    STF_REG_F0 = <STF_REG_int> _STF_REG_F0
    STF_REG_F1 = <STF_REG_int> _STF_REG_F1
    STF_REG_F2 = <STF_REG_int> _STF_REG_F2
    STF_REG_F3 = <STF_REG_int> _STF_REG_F3
    STF_REG_F4 = <STF_REG_int> _STF_REG_F4
    STF_REG_F5 = <STF_REG_int> _STF_REG_F5
    STF_REG_F6 = <STF_REG_int> _STF_REG_F6
    STF_REG_F7 = <STF_REG_int> _STF_REG_F7
    STF_REG_F8 = <STF_REG_int> _STF_REG_F8
    STF_REG_F9 = <STF_REG_int> _STF_REG_F9
    STF_REG_F10 = <STF_REG_int> _STF_REG_F10
    STF_REG_F11 = <STF_REG_int> _STF_REG_F11
    STF_REG_F12 = <STF_REG_int> _STF_REG_F12
    STF_REG_F13 = <STF_REG_int> _STF_REG_F13
    STF_REG_F14 = <STF_REG_int> _STF_REG_F14
    STF_REG_F15 = <STF_REG_int> _STF_REG_F15
    STF_REG_F16 = <STF_REG_int> _STF_REG_F16
    STF_REG_F17 = <STF_REG_int> _STF_REG_F17
    STF_REG_F18 = <STF_REG_int> _STF_REG_F18
    STF_REG_F19 = <STF_REG_int> _STF_REG_F19
    STF_REG_F20 = <STF_REG_int> _STF_REG_F20
    STF_REG_F21 = <STF_REG_int> _STF_REG_F21
    STF_REG_F22 = <STF_REG_int> _STF_REG_F22
    STF_REG_F23 = <STF_REG_int> _STF_REG_F23
    STF_REG_F24 = <STF_REG_int> _STF_REG_F24
    STF_REG_F25 = <STF_REG_int> _STF_REG_F25
    STF_REG_F26 = <STF_REG_int> _STF_REG_F26
    STF_REG_F27 = <STF_REG_int> _STF_REG_F27
    STF_REG_F28 = <STF_REG_int> _STF_REG_F28
    STF_REG_F29 = <STF_REG_int> _STF_REG_F29
    STF_REG_F30 = <STF_REG_int> _STF_REG_F30
    STF_REG_F31 = <STF_REG_int> _STF_REG_F31

    # 32 vector registers
    STF_REG_V0 = <STF_REG_int> _STF_REG_V0
    STF_REG_V1 = <STF_REG_int> _STF_REG_V1
    STF_REG_V2 = <STF_REG_int> _STF_REG_V2
    STF_REG_V3 = <STF_REG_int> _STF_REG_V3
    STF_REG_V4 = <STF_REG_int> _STF_REG_V4
    STF_REG_V5 = <STF_REG_int> _STF_REG_V5
    STF_REG_V6 = <STF_REG_int> _STF_REG_V6
    STF_REG_V7 = <STF_REG_int> _STF_REG_V7
    STF_REG_V8 = <STF_REG_int> _STF_REG_V8
    STF_REG_V9 = <STF_REG_int> _STF_REG_V9
    STF_REG_V10 = <STF_REG_int> _STF_REG_V10
    STF_REG_V11 = <STF_REG_int> _STF_REG_V11
    STF_REG_V12 = <STF_REG_int> _STF_REG_V12
    STF_REG_V13 = <STF_REG_int> _STF_REG_V13
    STF_REG_V14 = <STF_REG_int> _STF_REG_V14
    STF_REG_V15 = <STF_REG_int> _STF_REG_V15
    STF_REG_V16 = <STF_REG_int> _STF_REG_V16
    STF_REG_V17 = <STF_REG_int> _STF_REG_V17
    STF_REG_V18 = <STF_REG_int> _STF_REG_V18
    STF_REG_V19 = <STF_REG_int> _STF_REG_V19
    STF_REG_V20 = <STF_REG_int> _STF_REG_V20
    STF_REG_V21 = <STF_REG_int> _STF_REG_V21
    STF_REG_V22 = <STF_REG_int> _STF_REG_V22
    STF_REG_V23 = <STF_REG_int> _STF_REG_V23
    STF_REG_V24 = <STF_REG_int> _STF_REG_V24
    STF_REG_V25 = <STF_REG_int> _STF_REG_V25
    STF_REG_V26 = <STF_REG_int> _STF_REG_V26
    STF_REG_V27 = <STF_REG_int> _STF_REG_V27
    STF_REG_V28 = <STF_REG_int> _STF_REG_V28
    STF_REG_V29 = <STF_REG_int> _STF_REG_V29
    STF_REG_V30 = <STF_REG_int> _STF_REG_V30
    STF_REG_V31 = <STF_REG_int> _STF_REG_V31

    # Control and status registers
    # User
    STF_REG_CSR_USTATUS = <STF_REG_int> _STF_REG_CSR_USTATUS
    STF_REG_CSR_FFLAGS = <STF_REG_int> _STF_REG_CSR_FFLAGS
    STF_REG_CSR_FRM = <STF_REG_int> _STF_REG_CSR_FRM
    STF_REG_CSR_FCSR = <STF_REG_int> _STF_REG_CSR_FCSR
    STF_REG_CSR_UIE = <STF_REG_int> _STF_REG_CSR_UIE
    STF_REG_CSR_UTVEC = <STF_REG_int> _STF_REG_CSR_UTVEC
    STF_REG_CSR_UTVT = <STF_REG_int> _STF_REG_CSR_UTVT
    STF_REG_CSR_VSTART = <STF_REG_int> _STF_REG_CSR_VSTART
    STF_REG_CSR_VXSAT = <STF_REG_int> _STF_REG_CSR_VXSAT
    STF_REG_CSR_VXRM = <STF_REG_int> _STF_REG_CSR_VXRM
    STF_REG_CSR_VCSR = <STF_REG_int> _STF_REG_CSR_VCSR
    STF_REG_CSR_USCRATCH = <STF_REG_int> _STF_REG_CSR_USCRATCH
    STF_REG_CSR_UEPC = <STF_REG_int> _STF_REG_CSR_UEPC
    STF_REG_CSR_UCAUSE = <STF_REG_int> _STF_REG_CSR_UCAUSE
    STF_REG_CSR_UTVAL = <STF_REG_int> _STF_REG_CSR_UTVAL
    STF_REG_CSR_UIP = <STF_REG_int> _STF_REG_CSR_UIP
    STF_REG_CSR_UNXTI = <STF_REG_int> _STF_REG_CSR_UNXTI
    STF_REG_CSR_UINTSTATUS = <STF_REG_int> _STF_REG_CSR_UINTSTATUS
    STF_REG_CSR_USCRATCHCSW = <STF_REG_int> _STF_REG_CSR_USCRATCHCSW
    STF_REG_CSR_USCRATCHCSWL = <STF_REG_int> _STF_REG_CSR_USCRATCHCSWL

    # Supervisor
    STF_REG_CSR_SSTATUS = <STF_REG_int> _STF_REG_CSR_SSTATUS
    STF_REG_CSR_SIE = <STF_REG_int> _STF_REG_CSR_SIE
    STF_REG_CSR_STVEC = <STF_REG_int> _STF_REG_CSR_STVEC
    STF_REG_CSR_SCOUNTEREN = <STF_REG_int> _STF_REG_CSR_SCOUNTEREN
    STF_REG_CSR_STVT = <STF_REG_int> _STF_REG_CSR_STVT
    STF_REG_CSR_SSCRATCH = <STF_REG_int> _STF_REG_CSR_SSCRATCH
    STF_REG_CSR_SEPC = <STF_REG_int> _STF_REG_CSR_SEPC
    STF_REG_CSR_SCAUSE = <STF_REG_int> _STF_REG_CSR_SCAUSE
    STF_REG_CSR_STVAL = <STF_REG_int> _STF_REG_CSR_STVAL
    STF_REG_CSR_SIP = <STF_REG_int> _STF_REG_CSR_SIP
    STF_REG_CSR_SNXTI = <STF_REG_int> _STF_REG_CSR_SNXTI
    STF_REG_CSR_SINTSTATUS = <STF_REG_int> _STF_REG_CSR_SINTSTATUS
    STF_REG_CSR_SSCRATCHCSW = <STF_REG_int> _STF_REG_CSR_SSCRATCHCSW
    STF_REG_CSR_SSCRATCHCSWL = <STF_REG_int> _STF_REG_CSR_SSCRATCHCSWL
    STF_REG_CSR_SATP = <STF_REG_int> _STF_REG_CSR_SATP
    STF_REG_CSR_SENVCFG = <STF_REG_int> _STF_REG_CSR_SENVCFG

    # ???
    STF_REG_CSR_VSSTATUS = <STF_REG_int> _STF_REG_CSR_VSSTATUS
    STF_REG_CSR_VSIE = <STF_REG_int> _STF_REG_CSR_VSIE
    STF_REG_CSR_VSTVEC = <STF_REG_int> _STF_REG_CSR_VSTVEC
    STF_REG_CSR_VSSCRATCH = <STF_REG_int> _STF_REG_CSR_VSSCRATCH
    STF_REG_CSR_VSEPC = <STF_REG_int> _STF_REG_CSR_VSEPC
    STF_REG_CSR_VSCAUSE = <STF_REG_int> _STF_REG_CSR_VSCAUSE
    STF_REG_CSR_VSTVAL = <STF_REG_int> _STF_REG_CSR_VSTVAL
    STF_REG_CSR_VSIP = <STF_REG_int> _STF_REG_CSR_VSIP
    STF_REG_CSR_VSATP = <STF_REG_int> _STF_REG_CSR_VSATP

    # Machine
    STF_REG_CSR_MSTATUS = <STF_REG_int> _STF_REG_CSR_MSTATUS
    STF_REG_CSR_MISA = <STF_REG_int> _STF_REG_CSR_MISA
    STF_REG_CSR_MEDELEG = <STF_REG_int> _STF_REG_CSR_MEDELEG
    STF_REG_CSR_MIDELEG = <STF_REG_int> _STF_REG_CSR_MIDELEG
    STF_REG_CSR_MIE = <STF_REG_int> _STF_REG_CSR_MIE
    STF_REG_CSR_MTVEC = <STF_REG_int> _STF_REG_CSR_MTVEC
    STF_REG_CSR_MCOUNTEREN = <STF_REG_int> _STF_REG_CSR_MCOUNTEREN
    STF_REG_CSR_MTVT = <STF_REG_int> _STF_REG_CSR_MTVT
    STF_REG_CSR_MENVCFG = <STF_REG_int> _STF_REG_CSR_MENVCFG
    STF_REG_CSR_MSTATUSH = <STF_REG_int> _STF_REG_CSR_MSTATUSH
    STF_REG_CSR_MENVCFGH = <STF_REG_int> _STF_REG_CSR_MENVCFGH
    STF_REG_CSR_MSCRATCH = <STF_REG_int> _STF_REG_CSR_MSCRATCH
    STF_REG_CSR_MEPC = <STF_REG_int> _STF_REG_CSR_MEPC
    STF_REG_CSR_MCAUSE = <STF_REG_int> _STF_REG_CSR_MCAUSE
    STF_REG_CSR_MTVAL = <STF_REG_int> _STF_REG_CSR_MTVAL
    STF_REG_CSR_MIP = <STF_REG_int> _STF_REG_CSR_MIP
    STF_REG_CSR_MNXTI = <STF_REG_int> _STF_REG_CSR_MNXTI
    STF_REG_CSR_MINTSTATUS = <STF_REG_int> _STF_REG_CSR_MINTSTATUS
    STF_REG_CSR_MSCRATCHCSW = <STF_REG_int> _STF_REG_CSR_MSCRATCHCSW
    STF_REG_CSR_MSCRATCHCSWL = <STF_REG_int> _STF_REG_CSR_MSCRATCHCSWL

    # Machine Memory Protection
    STF_REG_CSR_PMPCFG0 = <STF_REG_int> _STF_REG_CSR_PMPCFG0
    STF_REG_CSR_PMPCFG1 = <STF_REG_int> _STF_REG_CSR_PMPCFG1
    STF_REG_CSR_PMPCFG2 = <STF_REG_int> _STF_REG_CSR_PMPCFG2
    STF_REG_CSR_PMPCFG3 = <STF_REG_int> _STF_REG_CSR_PMPCFG3
    STF_REG_CSR_PMPCFG4 = <STF_REG_int> _STF_REG_CSR_PMPCFG4
    STF_REG_CSR_PMPCFG5 = <STF_REG_int> _STF_REG_CSR_PMPCFG5
    STF_REG_CSR_PMPCFG6 = <STF_REG_int> _STF_REG_CSR_PMPCFG6
    STF_REG_CSR_PMPCFG7 = <STF_REG_int> _STF_REG_CSR_PMPCFG7
    STF_REG_CSR_PMPCFG8 = <STF_REG_int> _STF_REG_CSR_PMPCFG8
    STF_REG_CSR_PMPCFG9 = <STF_REG_int> _STF_REG_CSR_PMPCFG9
    STF_REG_CSR_PMPCFG10 = <STF_REG_int> _STF_REG_CSR_PMPCFG10
    STF_REG_CSR_PMPCFG11 = <STF_REG_int> _STF_REG_CSR_PMPCFG11
    STF_REG_CSR_PMPCFG12 = <STF_REG_int> _STF_REG_CSR_PMPCFG12
    STF_REG_CSR_PMPCFG13 = <STF_REG_int> _STF_REG_CSR_PMPCFG13
    STF_REG_CSR_PMPCFG14 = <STF_REG_int> _STF_REG_CSR_PMPCFG14
    STF_REG_CSR_PMPCFG15 = <STF_REG_int> _STF_REG_CSR_PMPCFG15
    STF_REG_CSR_PMPADDR0 = <STF_REG_int> _STF_REG_CSR_PMPADDR0
    STF_REG_CSR_PMPADDR1 = <STF_REG_int> _STF_REG_CSR_PMPADDR1
    STF_REG_CSR_PMPADDR2 = <STF_REG_int> _STF_REG_CSR_PMPADDR2
    STF_REG_CSR_PMPADDR3 = <STF_REG_int> _STF_REG_CSR_PMPADDR3
    STF_REG_CSR_PMPADDR4 = <STF_REG_int> _STF_REG_CSR_PMPADDR4
    STF_REG_CSR_PMPADDR5 = <STF_REG_int> _STF_REG_CSR_PMPADDR5
    STF_REG_CSR_PMPADDR6 = <STF_REG_int> _STF_REG_CSR_PMPADDR6
    STF_REG_CSR_PMPADDR7 = <STF_REG_int> _STF_REG_CSR_PMPADDR7
    STF_REG_CSR_PMPADDR8 = <STF_REG_int> _STF_REG_CSR_PMPADDR8
    STF_REG_CSR_PMPADDR9 = <STF_REG_int> _STF_REG_CSR_PMPADDR9
    STF_REG_CSR_PMPADDR10 = <STF_REG_int> _STF_REG_CSR_PMPADDR10
    STF_REG_CSR_PMPADDR11 = <STF_REG_int> _STF_REG_CSR_PMPADDR11
    STF_REG_CSR_PMPADDR12 = <STF_REG_int> _STF_REG_CSR_PMPADDR12
    STF_REG_CSR_PMPADDR13 = <STF_REG_int> _STF_REG_CSR_PMPADDR13
    STF_REG_CSR_PMPADDR14 = <STF_REG_int> _STF_REG_CSR_PMPADDR14
    STF_REG_CSR_PMPADDR15 = <STF_REG_int> _STF_REG_CSR_PMPADDR15
    STF_REG_CSR_PMPADDR16 = <STF_REG_int> _STF_REG_CSR_PMPADDR16
    STF_REG_CSR_PMPADDR17 = <STF_REG_int> _STF_REG_CSR_PMPADDR17
    STF_REG_CSR_PMPADDR18 = <STF_REG_int> _STF_REG_CSR_PMPADDR18
    STF_REG_CSR_PMPADDR19 = <STF_REG_int> _STF_REG_CSR_PMPADDR19
    STF_REG_CSR_PMPADDR20 = <STF_REG_int> _STF_REG_CSR_PMPADDR20
    STF_REG_CSR_PMPADDR21 = <STF_REG_int> _STF_REG_CSR_PMPADDR21
    STF_REG_CSR_PMPADDR22 = <STF_REG_int> _STF_REG_CSR_PMPADDR22
    STF_REG_CSR_PMPADDR23 = <STF_REG_int> _STF_REG_CSR_PMPADDR23
    STF_REG_CSR_PMPADDR24 = <STF_REG_int> _STF_REG_CSR_PMPADDR24
    STF_REG_CSR_PMPADDR25 = <STF_REG_int> _STF_REG_CSR_PMPADDR25
    STF_REG_CSR_PMPADDR26 = <STF_REG_int> _STF_REG_CSR_PMPADDR26
    STF_REG_CSR_PMPADDR27 = <STF_REG_int> _STF_REG_CSR_PMPADDR27
    STF_REG_CSR_PMPADDR28 = <STF_REG_int> _STF_REG_CSR_PMPADDR28
    STF_REG_CSR_PMPADDR29 = <STF_REG_int> _STF_REG_CSR_PMPADDR29
    STF_REG_CSR_PMPADDR30 = <STF_REG_int> _STF_REG_CSR_PMPADDR30
    STF_REG_CSR_PMPADDR31 = <STF_REG_int> _STF_REG_CSR_PMPADDR31
    STF_REG_CSR_PMPADDR32 = <STF_REG_int> _STF_REG_CSR_PMPADDR32
    STF_REG_CSR_PMPADDR33 = <STF_REG_int> _STF_REG_CSR_PMPADDR33
    STF_REG_CSR_PMPADDR34 = <STF_REG_int> _STF_REG_CSR_PMPADDR34
    STF_REG_CSR_PMPADDR35 = <STF_REG_int> _STF_REG_CSR_PMPADDR35
    STF_REG_CSR_PMPADDR36 = <STF_REG_int> _STF_REG_CSR_PMPADDR36
    STF_REG_CSR_PMPADDR37 = <STF_REG_int> _STF_REG_CSR_PMPADDR37
    STF_REG_CSR_PMPADDR38 = <STF_REG_int> _STF_REG_CSR_PMPADDR38
    STF_REG_CSR_PMPADDR39 = <STF_REG_int> _STF_REG_CSR_PMPADDR39
    STF_REG_CSR_PMPADDR40 = <STF_REG_int> _STF_REG_CSR_PMPADDR40
    STF_REG_CSR_PMPADDR41 = <STF_REG_int> _STF_REG_CSR_PMPADDR41
    STF_REG_CSR_PMPADDR42 = <STF_REG_int> _STF_REG_CSR_PMPADDR42
    STF_REG_CSR_PMPADDR43 = <STF_REG_int> _STF_REG_CSR_PMPADDR43
    STF_REG_CSR_PMPADDR44 = <STF_REG_int> _STF_REG_CSR_PMPADDR44
    STF_REG_CSR_PMPADDR45 = <STF_REG_int> _STF_REG_CSR_PMPADDR45
    STF_REG_CSR_PMPADDR46 = <STF_REG_int> _STF_REG_CSR_PMPADDR46
    STF_REG_CSR_PMPADDR47 = <STF_REG_int> _STF_REG_CSR_PMPADDR47
    STF_REG_CSR_PMPADDR48 = <STF_REG_int> _STF_REG_CSR_PMPADDR48
    STF_REG_CSR_PMPADDR49 = <STF_REG_int> _STF_REG_CSR_PMPADDR49
    STF_REG_CSR_PMPADDR50 = <STF_REG_int> _STF_REG_CSR_PMPADDR50
    STF_REG_CSR_PMPADDR51 = <STF_REG_int> _STF_REG_CSR_PMPADDR51
    STF_REG_CSR_PMPADDR52 = <STF_REG_int> _STF_REG_CSR_PMPADDR52
    STF_REG_CSR_PMPADDR53 = <STF_REG_int> _STF_REG_CSR_PMPADDR53
    STF_REG_CSR_PMPADDR54 = <STF_REG_int> _STF_REG_CSR_PMPADDR54
    STF_REG_CSR_PMPADDR55 = <STF_REG_int> _STF_REG_CSR_PMPADDR55
    STF_REG_CSR_PMPADDR56 = <STF_REG_int> _STF_REG_CSR_PMPADDR56
    STF_REG_CSR_PMPADDR57 = <STF_REG_int> _STF_REG_CSR_PMPADDR57
    STF_REG_CSR_PMPADDR58 = <STF_REG_int> _STF_REG_CSR_PMPADDR58
    STF_REG_CSR_PMPADDR59 = <STF_REG_int> _STF_REG_CSR_PMPADDR59
    STF_REG_CSR_PMPADDR60 = <STF_REG_int> _STF_REG_CSR_PMPADDR60
    STF_REG_CSR_PMPADDR61 = <STF_REG_int> _STF_REG_CSR_PMPADDR61
    STF_REG_CSR_PMPADDR62 = <STF_REG_int> _STF_REG_CSR_PMPADDR62
    STF_REG_CSR_PMPADDR63 = <STF_REG_int> _STF_REG_CSR_PMPADDR63

    # ???
    STF_REG_CSR_HSTATUS = <STF_REG_int> _STF_REG_CSR_HSTATUS
    STF_REG_CSR_HEDELEG = <STF_REG_int> _STF_REG_CSR_HEDELEG
    STF_REG_CSR_HIDELEG = <STF_REG_int> _STF_REG_CSR_HIDELEG
    STF_REG_CSR_HCOUNTEREN = <STF_REG_int> _STF_REG_CSR_HCOUNTEREN
    STF_REG_CSR_HGATP = <STF_REG_int> _STF_REG_CSR_HGATP

    # Machine Security Config Registers
    STF_REG_CSR_MSECCFG = <STF_REG_int> _STF_REG_CSR_MSECCFG
    STF_REG_CSR_MSECCFGH = <STF_REG_int> _STF_REG_CSR_MSECCFGH

    # Basic Machine Counters
    STF_REG_CSR_MCYCLE = <STF_REG_int> _STF_REG_CSR_MCYCLE
    STF_REG_CSR_MINSTRET = <STF_REG_int> _STF_REG_CSR_MINSTRET

    # Basic Machine Performance Monitoring Counters
    STF_REG_CSR_MCYCLEH = <STF_REG_int> _STF_REG_CSR_MCYCLEH
    STF_REG_CSR_MINSTRETH = <STF_REG_int> _STF_REG_CSR_MINSTRETH

    # Basic User Counters
    STF_REG_CSR_CYCLE = <STF_REG_int> _STF_REG_CSR_CYCLE
    STF_REG_CSR_TIME = <STF_REG_int> _STF_REG_CSR_TIME
    STF_REG_CSR_INSTRET = <STF_REG_int> _STF_REG_CSR_INSTRET

    # Vector
    STF_REG_CSR_VL = <STF_REG_int> _STF_REG_CSR_VL
    STF_REG_CSR_VTYPE = <STF_REG_int> _STF_REG_CSR_VTYPE
    STF_REG_CSR_VLENB = <STF_REG_int> _STF_REG_CSR_VLENB

    # Basic User Performance Monitoring Counters
    STF_REG_CSR_CYCLEH = <STF_REG_int> _STF_REG_CSR_CYCLEH
    STF_REG_CSR_TIMEH = <STF_REG_int> _STF_REG_CSR_TIMEH
    STF_REG_CSR_INSTRETH = <STF_REG_int> _STF_REG_CSR_INSTRETH

    # Machine Information Registers
    STF_REG_CSR_MVENDORID = <STF_REG_int> _STF_REG_CSR_MVENDORID
    STF_REG_CSR_MARCHID = <STF_REG_int> _STF_REG_CSR_MARCHID
    STF_REG_CSR_MIMPID = <STF_REG_int> _STF_REG_CSR_MIMPID
    STF_REG_CSR_MHARTID = <STF_REG_int> _STF_REG_CSR_MHARTID
    STF_REG_CSR_MCONFIGPTR = <STF_REG_int> _STF_REG_CSR_MCONFIGPTR

    STF_REG_INVALID = <STF_REG_int> _STF_REG_INVALID

cpdef enum STF_REG_OPERAND_TYPE:
    REG_RESERVED = <STF_REG_metadata_int> _REG_RESERVED
    REG_STATE = <STF_REG_metadata_int> _REG_STATE
    REG_SOURCE = <STF_REG_metadata_int> _REG_SOURCE
    REG_DEST = <STF_REG_metadata_int> _REG_DEST
